eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8070
spring:
  application:
    name: location
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      host: localhost
      port: 27017
      database: location
